package com.nuc.admin.dao;


import com.nuc.admin.domain.People;

import java.util.List;

public interface IPeopleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    int insert(People record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    People selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    List<People> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(People record);


    int listPeoplesCount(People people);


    List<People> listPeoples(People people);

    People getPeople(People people);

    int delPeoples(String[] ids);
}