package com.nuc.admin.dao;


import com.nuc.admin.domain.Rent;

import java.util.List;

public interface IRentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rentId);

    int delRents(String[] ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent
     *
     * @mbg.generated
     */
    int insert(Rent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent
     *
     * @mbg.generated
     */
    Rent selectByPrimaryKey(Integer rentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent
     *
     * @mbg.generated
     */
    List<Rent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Rent record);

    int updateRent(Rent rent);


    int listRentsCount(Rent rent);

    List<Rent> listRents(Rent rent);

    Rent getRent(Rent rent);
}